name: Run Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'TestBranch'  # Default branch to run the tests on

jobs:
  test:
    runs-on: windows-latest  # Run on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out the code from the repository
      with:
        ref: ${{ github.event.inputs.branch }}  # Use the branch input from the manual trigger

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Specify Java version 17
        distribution: 'temurin'  # Specify the Java distribution (Temurin is the recommended option)

    - name: Set ChromeDriver path and Chrome path
      run: |
        # Set the path to ChromeDriver and Chrome executable
        echo "CHROMEDRIVER_PATH=C:\\path\\to\\chromedriver" >> $GITHUB_ENV  # Set the path to your locally installed ChromeDriver
        echo "CHROME_PATH=C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" >> $GITHUB_ENV  # Set the path to your locally installed Chrome
        echo "CHROME_HEADLESS=false" >> $GITHUB_ENV  # Set Chrome to run in non-headless mode (default mode)

    - name: Run Tests
      run: mvn test  # Run the tests with Maven

    - name: Upload Extent Report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: extent-report
        path: path/to/your/extent-report.html  # Replace this with the actual path to your Extent Report file

    - name: Send Email with Extent Report
      uses: dawidd6/action-send-mail@v3  # GitHub Action to send an email
      with:
        server_address: smtp.gmail.com  # Use Gmail's SMTP server or any SMTP service you want
        server_port: 587  # SMTP port for Gmail
        username: ${{ secrets.EMAIL_USERNAME }}  # Use GitHub Secrets to store email credentials securely
        password: ${{ secrets.EMAIL_PASSWORD }}  # Use GitHub Secrets to store email credentials securely
        to: ramesh@navadhiti.com  # The recipient's email address
        from: ${{ secrets.EMAIL_USERNAME }}  # Sender's email address (use the same as the SMTP server)
        subject: 'Extent Report from GitHub Actions Test Run'
        body: |
          The test run has completed. Please find the Extent Report attached.
        attachments: path/to/your/extent-report.html  # Path to your Extent report generated by the test run
